# Generated by Django 2.2.6 on 2021-01-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondent',
            old_name='pos_key',
            new_name='position',
        ),
    ]
