# Generated by Django 2.2.6 on 2021-01-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20210126_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=210)),
                ('description', models.CharField(default='None', max_length=800)),
                ('review1', models.CharField(default='None', max_length=130)),
                ('review2', models.CharField(default='None', max_length=130)),
                ('review3', models.CharField(default='None', max_length=130)),
                ('num_responses', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='respondent',
            name='product_seq',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review1_rating', models.PositiveSmallIntegerField(default=0)),
                ('review2_rating', models.PositiveSmallIntegerField(default=0)),
                ('review3_rating', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Product')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Respondent')),
            ],
        ),
    ]
