# Generated by Django 2.2.6 on 2021-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20210127_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='additional',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='respondent',
            name='factors',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
