# Generated by Django 2.2.6 on 2021-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_product_amazon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='time_elapsed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
